# Generated by Django 5.2.8 on 2025-12-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='publications/')),
                ('date_publication', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
