# Generated by Django 5.2.8 on 2026-03-27 11:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero_identite', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro d'identité doit contenir exactement 11 chiffres", regex='^[0-9]{11}$')])),
                ('telephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Delocalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_propriete', models.CharField(choices=[('maison', 'Maison'), ('concession', 'Concession'), ('parcelle_vide', 'Parcelle vide'), ('autre', 'Autre')], max_length=20)),
                ('type_delocalisation', models.CharField(choices=[('deplacement', 'Délocalisation vers un autre lieu'), ('compensation', 'Compensation financière')], max_length=20)),
                ('ancienne_adresse', models.CharField(max_length=255)),
                ('ancienne_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ancienne_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('nouvelle_adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('nouvelle_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('nouvelle_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('montant_compensation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietes', to='core.personne')),
            ],
        ),
    ]
