# Generated by Django 5.2.8 on 2026-03-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_personne_delocalisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delocalisation',
            name='ancienne_adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='delocalisation',
            name='ancienne_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='delocalisation',
            name='ancienne_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
