# Generated by Django 5.2.8 on 2026-04-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelocalisationPlantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('postnom', models.CharField(max_length=100, verbose_name='Post-nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('photo', models.ImageField(upload_to='delocalisation_plantations/photos/', verbose_name='Photo')),
                ('type_piece_identite', models.CharField(choices=[('carte_nationale', "Carte d'identité nationale"), ('passeport', 'Passeport')], max_length=20, verbose_name="Type de pièce d'identité")),
                ('numero_piece_identite', models.CharField(max_length=50, verbose_name='Numéro de la pièce (nationale ou passeport)')),
                ('numero_permis_conduire', models.CharField(max_length=50, verbose_name='Numéro de permis de conduire')),
                ('attestation_naissance', models.FileField(upload_to='delocalisation_plantations/attestations/', verbose_name='Attestation de naissance')),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, help_text='Superficie de la plantation en mètres carrés', max_digits=10, null=True, verbose_name='Superficie (en m²)')),
                ('nature_culture', models.CharField(blank=True, help_text='Type de culture pratiquée sur la plantation', max_length=255, null=True, verbose_name='Nature de culture')),
                ('superficie_maison', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superficie de la maison (en m²)')),
                ('type_structure_maison', models.CharField(blank=True, choices=[('A', 'Type A'), ('B', 'Type B'), ('C', 'Type C'), ('D', 'Type D'), ('E', 'Type E')], max_length=1, null=True, verbose_name='Type de structure maison')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
            ],
            options={
                'verbose_name': 'Délocalisation de plantation',
                'verbose_name_plural': 'Délocalisations des plantations',
                'ordering': ['-date_enregistrement'],
            },
        ),
    ]
