# Generated by Django 5.2.8 on 2026-04-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delocalisationplantation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delocalisationplantation',
            name='attestation_naissance',
        ),
        migrations.RemoveField(
            model_name='delocalisationplantation',
            name='numero_piece_identite',
        ),
        migrations.RemoveField(
            model_name='delocalisationplantation',
            name='type_piece_identite',
        ),
        migrations.AddField(
            model_name='delocalisationplantation',
            name='numero_attestation_naissance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Attestation de naissance — Numéro d'attestation"),
        ),
        migrations.AddField(
            model_name='delocalisationplantation',
            name='numero_carte_electeur',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Carte d'électeur — Numéro nationale"),
        ),
        migrations.AddField(
            model_name='delocalisationplantation',
            name='numero_passeport',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Passeport — Numéro de passeport'),
        ),
        migrations.AlterField(
            model_name='delocalisationplantation',
            name='numero_permis_conduire',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Permis de conduire — Numéro de permis'),
        ),
    ]
