# Generated by Django 5.2.8 on 2026-04-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_delocalisationplantation_attestation_naissance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delocalisationplantation',
            options={'ordering': ['-date_enregistrement'], 'verbose_name': 'CPD plantation agricole', 'verbose_name_plural': 'CPD plantations agricoles'},
        ),
    ]
