# Generated by Django 5.2.8 on 2026-04-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_delocalisationplantation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='delocalisationplantation',
            name='type_piece_identite',
            field=models.CharField(choices=[('carte_electeur', "Carte d'électeur"), ('passeport', 'Passeport'), ('permis_conduire', 'Permis de conduire'), ('attestation_naissance', 'Attestation de naissance')], default='carte_electeur', max_length=25, verbose_name="Type de pièce d'identité"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delocalisationplantation',
            name='numero_attestation_naissance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro d'attestation de naissance"),
        ),
        migrations.AlterField(
            model_name='delocalisationplantation',
            name='numero_carte_electeur',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro nationale (carte d'électeur)"),
        ),
        migrations.AlterField(
            model_name='delocalisationplantation',
            name='numero_passeport',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de passeport'),
        ),
        migrations.AlterField(
            model_name='delocalisationplantation',
            name='numero_permis_conduire',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de permis de conduire'),
        ),
    ]
