# Generated by Django 5.2.8 on 2026-04-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delocalisationplantation_type_piece_identite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delocalisationplantation',
            name='site_adresse',
            field=models.CharField(blank=True, help_text="Le site ou l'adresse du champ", max_length=255, null=True, verbose_name='Site ou adresse'),
        ),
        migrations.AlterField(
            model_name='delocalisationplantation',
            name='nature_culture',
            field=models.CharField(blank=True, help_text='Type de culture pratiquée sur le champ', max_length=255, null=True, verbose_name='Nature de culture'),
        ),
        migrations.AlterField(
            model_name='delocalisationplantation',
            name='superficie',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Superficie du champs en mètres carrés', max_digits=10, null=True, verbose_name='Superficie du champs (en m²)'),
        ),
        migrations.AlterField(
            model_name='delocalisationplantation',
            name='superficie_maison',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superficie parcelle (en m²)'),
        ),
    ]
