# Generated by Django 5.2.8 on 2026-08-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delocalisationplantation_site_adresse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delocalisationplantation',
            options={'ordering': ['-date_enregistrement'], 'verbose_name': 'CPD (Commission Prov. de Délocalisation)', 'verbose_name_plural': 'CPD (Commission Prov. de Délocalisation)'},
        ),
    ]
