# Generated by Django 5.2.8 on 2026-08-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('telephone', models.CharField(max_length=30)),
                ('entreprise', models.CharField(blank=True, default='', max_length=120)),
                ('service', models.CharField(choices=[('Internet & Connectivité', 'Internet & Connectivité'), ('Solutions IT pour entreprises', 'Solutions IT pour entreprises'), ('Cybersécurité', 'Cybersécurité'), ('Développement Web & Applications', 'Développement Web & Applications'), ('Support & Maintenance', 'Support & Maintenance'), ('Équipements informatiques', 'Équipements informatiques'), ('Domotique / Maison intelligente', 'Domotique / Maison intelligente')], max_length=64)),
                ('description', models.TextField()),
                ('budget', models.CharField(blank=True, default='', max_length=120)),
                ('delai', models.CharField(blank=True, default='', max_length=120)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('traite', 'Traité'), ('rejete', 'Rejeté / spam')], db_index=True, default='nouveau', max_length=16)),
                ('notes_internes', models.TextField(blank=True, default='')),
                ('source_origin', models.CharField(blank=True, default='', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande de devis ALTIS',
                'verbose_name_plural': 'Demandes de devis ALTIS',
                'db_table': 'altis_devis_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', '-created_at'], name='altis_email_date_idx')],
            },
        ),
    ]
